### ISSUE TITLE
Nil pointer panic when IPFS_URL is empty

### ISSUE THREAD

**Issue by DRK3** [trustbloc/orb#531]
Currently there is no panic in the code listed bellow because we initialize ipfsReader to global ipfs later on. However, we should think about if this global fallback should be configurable too. We might have cases that our clients will not want to go to IPFS (period). Here is the setup for not requiring IPFS: 1. remove IPFS_URL, 2. remove ipfs container (and dependencies), 3. make sure that your cas type is set to local.

In `resolver.go`, this is causing a failure:

```
if h.ipfsReader != nil {
	// last resort - try ipfs if reader configured
	return h.getAndStoreDataFromIPFS(cid)
}
```

**Comment by DRK3** [comment]
Not an issue anymore

**Comment by sandrask** [comment]
Currently, it is not an issue since in the current code we initialize ipfsReader to global ipfs later on. However, we should think about if this global fallback should be configurable too. We might have cases that our clients will not want to go to IPFS (period). Here is the setup for not requiring IPFS: 1. remove IPFS_URL, 2. remove ipfs container (and dependencies), 3. make sure that your cas type is set to local. https://github.com/trustbloc/orb/pull/533
